### YamlMime:UniversalReference
items:
  - uid: App
    id: App
    name: App
    summary: >-
      Constructor takes in properties to initialize the app and create the state
      object
    fullName: App
    type: Class
    children:
      - App.#ctor
      - App#render
    langs:
      - js
  - id: App.#ctor
    uid: App.#ctor
    parent: App
    name: App(props)
    fullName: App.App(props)
    summary: ''
    type: Constructor
    syntax:
      parameters:
        - id: props
          type:
            - object
          description: >-
            Should contain a property 'pca' that's as PublicClientApplication()
            object
          optional: true
      content: new App(props)
    langs:
      - js
  - uid: App#render
    id: App#render
    parent: App
    name: render()
    summary: Renders the component
    fullName: App.render()
    type: Function
    syntax:
      content: function render()
    langs:
      - js
