name: QA branch review

on:
  push:
    branches:
      - qa
jobs:
  openPrToReview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Latest version ready to QA
          title: Custom title
          body: Please review https://yellow-sand-098426110.azurestaticapps.net/
          branch: main
          assignees: aj-stackingyourtech
          reviewers: aj-stackingyourtech
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
